### ISSUE TITLE
Missing documentation for redirect_uri

### ISSUE THREAD

**Issue by cinemont** [Herohtar/netlify-cms-oauth-firebase#6]
This line is just missing some documentation, what exactly are we meant to provide here?

https://github.com/Herohtar/netlify-cms-oauth-firebase/blob/89b6d27f080d6f27c346a1b7af8ca4e624e66a2d/functions/index.js#L43

Sorry, I'm not familiar with the oauth pipeline, perhaps it's an obvious answer.

**Comment by cinemont** [comment]
From the github docs, if I've correctly understood it's meant to redirect back to the 'application'
https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/

However with netlify CMS it's meant to work local and online, so this could be a number of URLs. Would it be possible to get this from the request param, rather than passing in a value?

**Comment by Herohtar** [comment]
My setup instructions don't mention it because it's not required, and the instructions are meant to be the bare minimum necessary to get you going. It's just there to allow you to redirect the user to a different page after authorization; if you leave it blank you'll just be redirected back to the original page the authorization request was sent from.

**Comment by cinemont** [comment]
Ah ok! Thanks for that, that's good to know.
