### ISSUE TITLE
OAuth closing the window but not authenticating

### ISSUE THREAD

**Issue by ghost** [Herohtar/netlify-cms-oauth-firebase#9]
It is logging into github but then it is returning, closing the window and it is not authenticated to get to the CMS.  

I've tried local and on firebase hosting.

Here is what I am seeing:
https://www.loom.com/share/caee6ea5cc034e8a8758876025880944

**Comment by ghost** [comment]
Ok, it was a billing account (your last comment in the readme).  It does work on the environment now, but not working for localhost, which for now is fine.  Any suggestions on getting it to work locally?

**Comment by Herohtar** [comment]
It has been a long time since I have done any work with Netlify CMS, so I don't actually remember if I was able to use this when running locally or not. I know you have to be actually serving the page via a local HTTP server, and make sure that all the necessary domain references are configured properly, so I'd recommend taking a look at that.
